//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Amoozeshgah.WebReferences.ir.shaparak.pec {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OnlineMultiplexedSalePaymentServiceSoap", Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/OnlineMultiplexedSalePaymentService")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClientPaymentResponseDataBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClientPaymentRequestDataBase))]
    public partial class OnlineMultiplexedSalePaymentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MultiplexedSalePaymentRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OnlineMultiplexedSalePaymentService() {
            this.Url = global::Amoozeshgah.WebReferences.Properties.Settings.Default.Amoozeshgah_WebReferences_ir_shaparak_pec_OnlineMultiplexedSalePaymentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MultiplexedSalePaymentRequestCompletedEventHandler MultiplexedSalePaymentRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://pec.Shaparak.ir/NewIPGServices/Sale/OnlineMultiplexedSalePaymentService/M" +
            "ultiplexedSalePaymentRequest", RequestNamespace="https://pec.Shaparak.ir/NewIPGServices/Sale/OnlineMultiplexedSalePaymentService", ResponseNamespace="https://pec.Shaparak.ir/NewIPGServices/Sale/OnlineMultiplexedSalePaymentService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientSaleResponseData MultiplexedSalePaymentRequest(ClientMultiplexedSalePaymentRequestData requestData) {
            object[] results = this.Invoke("MultiplexedSalePaymentRequest", new object[] {
                        requestData});
            return ((ClientSaleResponseData)(results[0]));
        }
        
        /// <remarks/>
        public void MultiplexedSalePaymentRequestAsync(ClientMultiplexedSalePaymentRequestData requestData) {
            this.MultiplexedSalePaymentRequestAsync(requestData, null);
        }
        
        /// <remarks/>
        public void MultiplexedSalePaymentRequestAsync(ClientMultiplexedSalePaymentRequestData requestData, object userState) {
            if ((this.MultiplexedSalePaymentRequestOperationCompleted == null)) {
                this.MultiplexedSalePaymentRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMultiplexedSalePaymentRequestOperationCompleted);
            }
            this.InvokeAsync("MultiplexedSalePaymentRequest", new object[] {
                        requestData}, this.MultiplexedSalePaymentRequestOperationCompleted, userState);
        }
        
        private void OnMultiplexedSalePaymentRequestOperationCompleted(object arg) {
            if ((this.MultiplexedSalePaymentRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MultiplexedSalePaymentRequestCompleted(this, new MultiplexedSalePaymentRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/OnlineMultiplexedSalePaymentService")]
    public partial class ClientMultiplexedSalePaymentRequestData : ClientPaymentRequestDataBase {
        
        private Account[] multiplexedAccountsField;
        
        /// <remarks/>
        public Account[] MultiplexedAccounts {
            get {
                return this.multiplexedAccountsField;
            }
            set {
                this.multiplexedAccountsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/OnlineMultiplexedSalePaymentService")]
    public partial class Account {
        
        private long amountField;
        
        private string payIdField;
        
        /// <remarks/>
        public long Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string PayId {
            get {
                return this.payIdField;
            }
            set {
                this.payIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClientSaleResponseData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/OnlineMultiplexedSalePaymentService")]
    public partial class ClientPaymentResponseDataBase {
        
        private long tokenField;
        
        private string messageField;
        
        private short statusField;
        
        /// <remarks/>
        public long Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public short Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/OnlineMultiplexedSalePaymentService")]
    public partial class ClientSaleResponseData : ClientPaymentResponseDataBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClientMultiplexedSalePaymentRequestData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/OnlineMultiplexedSalePaymentService")]
    public partial class ClientPaymentRequestDataBase {
        
        private string loginAccountField;
        
        private long amountField;
        
        private long orderIdField;
        
        private string callBackUrlField;
        
        private string additionalDataField;
        
        private string originatorField;
        
        /// <remarks/>
        public string LoginAccount {
            get {
                return this.loginAccountField;
            }
            set {
                this.loginAccountField = value;
            }
        }
        
        /// <remarks/>
        public long Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public long OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public string CallBackUrl {
            get {
                return this.callBackUrlField;
            }
            set {
                this.callBackUrlField = value;
            }
        }
        
        /// <remarks/>
        public string AdditionalData {
            get {
                return this.additionalDataField;
            }
            set {
                this.additionalDataField = value;
            }
        }
        
        /// <remarks/>
        public string Originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MultiplexedSalePaymentRequestCompletedEventHandler(object sender, MultiplexedSalePaymentRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MultiplexedSalePaymentRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MultiplexedSalePaymentRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientSaleResponseData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientSaleResponseData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591