//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amoozeshgah.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RequiredResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequiredResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amoozeshgah.Resource.RequiredResx", typeof(RequiredResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کد کلاس را وارد نمایید.
        /// </summary>
        public static string ClassCodeError {
            get {
                return ResourceManager.GetString("ClassCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام کلاس را وارد نمایید.
        /// </summary>
        public static string ClassNameNameError {
            get {
                return ResourceManager.GetString("ClassNameNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کد کلاس را وارد نمایید.
        /// </summary>
        public static string ClassroomCodeError {
            get {
                return ResourceManager.GetString("ClassroomCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام کلاس را وارد نمایید.
        /// </summary>
        public static string ClassroomNameError {
            get {
                return ResourceManager.GetString("ClassroomNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام دپارتمان را وارد نمایید.
        /// </summary>
        public static string DepartmentNameError {
            get {
                return ResourceManager.GetString("DepartmentNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع دپارتمان را مشخص کنید.
        /// </summary>
        public static string DepartmentTypeNameError {
            get {
                return ResourceManager.GetString("DepartmentTypeNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام زبان را وارد نمایید.
        /// </summary>
        public static string LanguageNameError {
            get {
                return ResourceManager.GetString("LanguageNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام  پدر را وارد نمایید.
        /// </summary>
        public static string StudentFatherNameError {
            get {
                return ResourceManager.GetString("StudentFatherNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام خانوادگی را وارد نمایید.
        /// </summary>
        public static string StudentLastNameError {
            get {
                return ResourceManager.GetString("StudentLastNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام را وارد نمایید.
        /// </summary>
        public static string StudentNameError {
            get {
                return ResourceManager.GetString("StudentNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کد ترم را وارد نمایید.
        /// </summary>
        public static string TermCodeError {
            get {
                return ResourceManager.GetString("TermCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تاریخ پایان ترم را مشخص کنید.
        /// </summary>
        public static string TermEndDateError {
            get {
                return ResourceManager.GetString("TermEndDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام ترم را وارد نمایید.
        /// </summary>
        public static string TermNameError {
            get {
                return ResourceManager.GetString("TermNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تاریخ آغاز ترم را مشخص کنید.
        /// </summary>
        public static string TermStartDateError {
            get {
                return ResourceManager.GetString("TermStartDateError", resourceCulture);
            }
        }
    }
}
