//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amoozeshgah.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TeacherRegisterResxInvalid {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TeacherRegisterResxInvalid() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amoozeshgah.Resource.TeacherRegisterResxInvalid", typeof(TeacherRegisterResxInvalid).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تاریخ تولد را به درستی وارد نمایید.
        /// </summary>
        internal static string BirthDateInvalid {
            get {
                return ResourceManager.GetString("BirthDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا محل سکونت را به درستی وارد نمایید.
        /// </summary>
        internal static string CityOfLocationIdInvalid {
            get {
                return ResourceManager.GetString("CityOfLocationIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام پدر را به درستی وارد نمایید.
        /// </summary>
        internal static string FatherNameInvalid {
            get {
                return ResourceManager.GetString("FatherNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام را به درستی وارد نمایید.
        /// </summary>
        internal static string FirstNameInvalid {
            get {
                return ResourceManager.GetString("FirstNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام خانوادگی را به درستی وارد نمایید.
        /// </summary>
        internal static string LastNameInvalid {
            get {
                return ResourceManager.GetString("LastNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تلفن همراه را به درستی وارد نمایید.
        /// </summary>
        internal static string MobileNumberInvalid {
            get {
                return ResourceManager.GetString("MobileNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کد ملی را به درستی وارد نمایید.
        /// </summary>
        internal static string NationalCodeInvalid {
            get {
                return ResourceManager.GetString("NationalCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام خانوادگی ولی را به درستی وارد نمایید.
        /// </summary>
        internal static string ParentFamilyInvalid {
            get {
                return ResourceManager.GetString("ParentFamilyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تلفن ثابت را به درستی وارد نمایید.
        /// </summary>
        internal static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا محل تولد را به درستی وارد نمایید.
        /// </summary>
        internal static string PlaceOfBirthIdInvalid {
            get {
                return ResourceManager.GetString("PlaceOfBirthIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا جنسیت را به درستی وارد نمایید.
        /// </summary>
        internal static string SexIdInvalid {
            get {
                return ResourceManager.GetString("SexIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تاریخ تولد را وارد نمایید.
        /// </summary>
        internal static string TeacherBirthDateError {
            get {
                return ResourceManager.GetString("TeacherBirthDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کد مدرس را وارد نمایید.
        /// </summary>
        internal static string TeacherCodeError {
            get {
                return ResourceManager.GetString("TeacherCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام  پدر را وارد نمایید.
        /// </summary>
        internal static string TeacherFatherNameError {
            get {
                return ResourceManager.GetString("TeacherFatherNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام را وارد نمایید.
        /// </summary>
        internal static string TeacherFirstNameError {
            get {
                return ResourceManager.GetString("TeacherFirstNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام خانوادگی را وارد نمایید.
        /// </summary>
        internal static string TeacherLastNameError {
            get {
                return ResourceManager.GetString("TeacherLastNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تلفن همراه را وارد نمایید.
        /// </summary>
        internal static string TeacherMobileNumberError {
            get {
                return ResourceManager.GetString("TeacherMobileNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کد ملی را وارد نمایید.
        /// </summary>
        internal static string TeacherNationalCodeError {
            get {
                return ResourceManager.GetString("TeacherNationalCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تلفن ثابت را وارد نمایید.
        /// </summary>
        internal static string TeacherPhoneNumberError {
            get {
                return ResourceManager.GetString("TeacherPhoneNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا محل تولد را وارد نمایید.
        /// </summary>
        internal static string TeacherPlaceOfBirthError {
            get {
                return ResourceManager.GetString("TeacherPlaceOfBirthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا جنسیت را وارد نمایید.
        /// </summary>
        internal static string TeacherSexIdError {
            get {
                return ResourceManager.GetString("TeacherSexIdError", resourceCulture);
            }
        }
    }
}
